#+Title:  Comcx's BLOG.index.org
#+AUTHOR: Comcx



#+SETUPFILE: org-themes/setup/theme-readtheorg.setup
#+HTML_HEAD: <style>pre.src{background:#343131;color:white;} </style>
#+HTML_HEAD: <style> #content{max-width:1800px;}</style>
#+HTML_HEAD: <style> p{max-width:800px;}</style>


** What topics may appear in this BOLG

Functional Programming, アニメ, 文学, Music, Games.



** Me, personally ...

I'm *Comcx*

This is a very simple and light-weight personal blog.
I am just trying to make things simple and stupid.

This blog may mainly contain articles on _Math_, _Functional Programming_, _Linguistics_ and _Animations_.
I'm just a person who's trying to get better understanding of the world and
to get better programming skills. My goal is to *create a programming language* which can
satisfy me while programming.

I tried to program with /C++,/ /Scala,/ /Haskell,/ /Racket/ and many other interesting programming languages.
They all in a sense makes me get better understanding of programming(especially Scala and Haskell).

The life is short and I may not be smart enough to achieve my goal, but I really love all these things.
The articles and ideas may looks stupid, but I think they will become valuable some day in the future.




The last thing, if you want to find me, go to this page of /comcx.fun,/ and read me again.



** Articles








