#+Title:  Tail recursion optimization
#+Author: Comcx

#+SETUPFILE: theme-readtheorg-local.setup


Many algorithms can be expressed concisely and elegantly in functional languages with recursions.
However, not all languages support automatic optimizations respect to functional algorithms and,
some languages(such as /Scala/), although support basic =@tailrec= optimizations by code transformation,
they still can not do some agressive tailrec optimizations such as =CPS tailrec=.

Therefore, we need to transform programs by hand. With this technique, we can use functional style
fearlessly for that we can translate our code into traditional imperative ways.

In studying this, *Scala* can play an important role in tranlating our programs since /Scala/ support
many different programming strategies. To make our method more impressive, we will finally try to translate
programs into effective *C++* codes.

We follow this program route:
#+BEGIN_SRC 
Haskell ==> Scala ==> C++
#+END_SRC

(This is just a try, still not sure if I can make it :-)


** Tailrec strategies

*** Linear recursion
**** Formalization
To make things simple but not stupid, we firstly only focus on recursions whose
last expression only contains one recursion
(which means we do not discuss tree recursion right now).

#+BEGIN_SRC haskell
rec 1 = some value
rec x = f x (rec (h x))
#+END_SRC

Now we unfold this recursion:
#+BEGIN_SRC haskell
rec x = f x $ f (h x) $ f (h $ h x) $ f (h $ h $ h x) $ ... $ f (h $ h $ ... $ h $ x) $ (some value)
#+END_SRC

Hummmmm, it looks even more complex...
I now have two guesses on how to do tailrec for codes like this:
1) Build from bottom or reverse order
2) Do /CPS/ transformation

Let's try the first one first.
To build from bottom, we need to know the most important parameter: =(h $ h $ ... $ x)=.
To know this parameter, we need to know how many times the function =h= was
applied to =x=. We can find some clues from the terminating pattern of =rec=.

**** Reverse order
- Our current problem:

  #+BEGIN_SRC 
  We have a function (h :: a -> a) which do transformations of x and
  we need to figure out that how many times h applied to x in order to
  reach the value '1'(some constant or pattern) in the terminating definiton of rec.
  #+END_SRC

***** *If h is reversible(noted h', i.e. h . h' = id)*

    we can build from bottom!
    Notice that we need to pass our value of each layer to upper layer,
    so we need one more parameter to record our current result.
#+BEGIN_SRC haskell
reverseBuild f h x res = f x res
reverseBuild f h y res = reverseBuild f h (h' y) (f y res)
#+END_SRC
    * use foldl, foldr?

***** *else h is not reversible:(*

    well, which means we can't get results from bottom, we have to start from
    head since we can not calculate (h $ h $ ... $ x). Maybe we need another strategy.

***** *To change order... How about =Monoid=?*

    Suppose we want to get the sum of a list:
#+BEGIN_SRC haskell
sum [] = 0
sum (x:xs) = x + sum xs
#+END_SRC
    where, =(+)= becomes the function =f=.

    Since (a + b) + c === a + (b + c),
    we can reverse the calculation order
#+BEGIN_SRC haskell
a + (b + (c + d))
#+END_SRC
    to
#+BEGIN_SRC haskell
((a + b) + c) + d
#+END_SRC
    It's just like to say that, we can change the calculation of
#+BEGIN_SRC haskell
x (h x) (h $ h x) ... (h $ h $ ... $ h x)
#+END_SRC
    with =f=.

    Let's try to implement this transformation with our general code:
#+BEGIN_SRC haskell
reverseOrder f h 1 res = res
reverseOrder f h x res = reverseOrder f h (h x) (f x (h x))
#+END_SRC
    This time we don't need =h'=!

***** *Being inspired by monoid, maybe be we can again generize our 'monoid approach' a little bit*

    This time instead of requiring f to be satisfiled by monoid law,
    we ourselves try to find a function =g= which satisfy the following law:
#+BEGIN_SRC haskell
g (g a b) c = f a (f b c)
#+END_SRC
    Now we can use our trick again:
#+BEGIN_SRC haskell
reverseOrder' g h 1 res = res
reverseOrder' g h x res = reverseOrder' g h (h x) (g x (h x))
#+END_SRC

    Even more general(although harder...), we can generalize function =h= too.
    Suppose we have our special function =g= and a new h function =p=.
    
    We have general rule:
#+BEGIN_SRC haskell
g (g x (p x)) (p $ p x) = f x (f (h x) (h $ h x))
or(with extra start x0)
g (g (g a x) (p x)) (p $ p x) = f x (f (h x) (h $ (h x)))
#+END_SRC
    What's more? We may Just add a new start data x0(just like foldl :-)

    The final version with extra x0(a is x0 at first):
#+BEGIN_SRC haskell
reverseOrder'' g p a 1 res = res
reverseOrder'' g p a x res = reverseOrder'' g p (p x) (g a x)
#+END_SRC
   
***** *Well, if we're not lucky.. we can't find a reverse h' nor monoid structure...*
     
    Two options:
    1) We still calculate from the beginning, but we pass the result as a =List= of (h $ ..x)s.
        But this is not efficient and ugly...
    2) Maybe it's time for our /CPS/ approach...

Time for the second idea!
**** CPS trasformation

CPS is a tool to convert recursive code to *tail call*.(note that this is different from tailrec).
Recall our =rec= function:
#+BEGIN_SRC haskell
rec 1 = some value
rec x = f x (rec (h x))
#+END_SRC

to /CPS/ style =>
#+BEGIN_SRC haskell
rec 1 c = c value
rec x c = rec (h x) (c . (f x))
#+END_SRC
It looks like we are just building our unfolded function chain.
Instead of accumulating results and values, we accumulate calculations(functions).

In fact, CPS can be used to convert any recursive function to tail-call form.
With CPS, we can build our executing stack from heap.

**** Summary
We have discussed several optimizations may be applied to list recursions.
Let's recap!

***** Tailrec
****** Calculating from bottom if reversible
****** Reverse calculation order
- By Monoid structure
- By special function g with specific rules
****** CPS transformation 

***** Dynamic Programming

*** Tree recursion
Well, it seems that linear tailrec is not easy now, how about tree tailrec?
**** Two-branch tree recursion
***** Formalization
#+BEGIN_SRC haskell
rec 1 = some value
rec x = f x (rec (g x)) (rec (h x))
#+END_SRC
If we unfold thie expression, this expression can be a very large binary-tree.
#+BEGIN_SRC 
                               f x
                     /                     \
          f $ g x                                 f $ h x
        /         \                            /           \
f $ g x $ g x     f $ g x $ h x    f $ h x $ g x            f $ h x $ h x

...
#+END_SRC
It looks like we are traversing all possible permutations of function =g= and =h= compositions

***** A simple try 

A very simple idea is that if we can tailrec =rec=, then we want to cache result of last step:
#+BEGIN_SRC haskell
rec' x a 
  = p (rec x) a
  = p (f x (rec (g x)) (rec (h x))) a
#+END_SRC
What if...
#+BEGIN_SRC haskell
p (f x (rec (g x)) (rec (h x))) a 
  = (rec (g x)) `f x` (rec (h x)) `p` a
  if f x a b == a `q` x `q` b
  = (rec (g x)) `q` x `q` (rec (h x)) `p` a
  = (rec (g x)) `q` x `q` (p (rec (h x)) a)
  = (rec (g x)) `q` x `q` (rec' (h x) a)
  if p == q
  = (rec (g x)) `p` x `p` (rec' (h x) a)
  if (a `p` b) `p` c == a `p` (b `p` c)
  = (rec (g x)) `p` (x `p` (rec' (h x) a))
  = p (rec (g x)) (p x (rec' (h x) a))
  = rec' (g x) (p x (rec' (h x) a))
#+END_SRC
Wait! we have made too many assumptions!
Let's list them all:
#+BEGIN_SRC
1. rec' x a = p (rec x) a
2. f x a b = a `p` x `p` b
3. (a `p` x) `p` b = a `p` (x `p` b)
#+END_SRC
In words, we can find a function =p=, which 
1) can be expressed as a composition of
   raw tree recursion version and a accumulation value
2) Function =f= can in raw tree recursion can be decomposed as compositions of function =p=.
3) Function =p= satisfy _Monoid law_.

These constraints looks really strict and ugly...
The first condition is easy to reach since we can simply build a function =p=.
The second is hard. we need to decompose =f= to our built function =p=.
Well, I want to have a try.

Can this strategy solve =fib= problem?
#+BEGIN_SRC haskell
fib 0 = 0
fib 1 = 1
fib n = fib (n-1) + fib (n-2)
#+END_SRC
#+BEGIN_SRC haskell
rec x = f x (rec (g x)) (rec (h x))

rec = fib
f x a b = a + b
g = (minus 1)
h = (minus 2)
#+END_SRC
OK, Let's build function =p=.
#+BEGIN_SRC haskell
fib' n a 
  = fib n + a
  = fib (n-1) + fib (n-2) + a
  = fib (n-1) + fib' (n-2) a
  = fib' (n-1) (fib' (n-2) a)
#+END_SRC
Therefore,
#+BEGIN_SRC haskell
fib' 0 a = a
fib' 1 a = 1 + a
fib' n a = fib' (n-1) (fib' (n-2) a)
#+END_SRC
We succeeded!
However, this is just our first baby step, this is just =tail call=, not =tailrec=.



**** N-branch tree recursion

** Examples
*** Selection sort
*** Fibonacci
*** Permutations










